// sources/icloud-workspace/seis-digital-experience-foundation/runtime/server-upload-bundle/source/polyglot/vue/ReadinessSignal.vue
<script setup>
const ReadinessSignal = {
  lane: "vue",
  status: "reference",
  score: 96,
  reducedMotionSafe: true,
  runtimeWeight: "dependency-light"
};
</script>

<template>
  <section
    :data-readiness-signal="ReadinessSignal.lane"
    :data-status="ReadinessSignal.status"
    :data-score="ReadinessSignal.score"
    :data-reduced-motion-safe="ReadinessSignal.reducedMotionSafe"
  >
    polyglot-foundation
  </section>
</template>

// sources/icloud-workspace/seis-digital-experience-foundation/polyglot/tsx/ReadinessSignal.tsx
type ReadinessSignal = {
  lane: "tsx";
  status: "reference";
  score: 108;
  reducedMotionSafe: true;
  runtimeWeight: "dependency-light";
};

const readinessSignal: ReadinessSignal = {
  lane: "tsx",
  status: "reference",
  score: 108,
  reducedMotionSafe: true,
  runtimeWeight: "dependency-light"
};

export function ReadinessSignalView() {
  return (
    <section
      data-readiness-signal={readinessSignal.lane}
      data-status={readinessSignal.status}
      data-score={readinessSignal.score}
      data-reduced-motion-safe={readinessSignal.reducedMotionSafe}
    >
      polyglot-foundation
    </section>
  );
}
