// sources/icloud-workspace/seis-digital-experience-foundation/runtime/server-upload-bundle/source/polyglot/jsx/ReadinessSignal.jsx
const ReadinessSignal = {
  lane: "jsx",
  status: "reference",
  score: 108,
  reducedMotionSafe: true,
  runtimeWeight: "dependency-light"
};

export function ReadinessSignalView() {
  return (
    <section
      data-readiness-signal={ReadinessSignal.lane}
      data-status={ReadinessSignal.status}
      data-score={ReadinessSignal.score}
      data-reduced-motion-safe={ReadinessSignal.reducedMotionSafe}
    >
      polyglot-foundation
    </section>
  );
}

// sources/icloud-workspace/seis-digital-experience-foundation/runtime/server-upload-bundle/source/polyglot/vue/ReadinessSignal.vue
<script setup>
const ReadinessSignal = {
  lane: "vue",
  status: "reference",
  score: 96,
  reducedMotionSafe: true,
  runtimeWeight: "dependency-light"
};
</script>

<template>
  <section
    :data-readiness-signal="ReadinessSignal.lane"
    :data-status="ReadinessSignal.status"
    :data-score="ReadinessSignal.score"
    :data-reduced-motion-safe="ReadinessSignal.reducedMotionSafe"
  >
    polyglot-foundation
  </section>
</template>
